### ISSUE TITLE
Schedule Shift Edit

### ISSUE THREAD

**Issue by bethgrace5** [bethgrace5/sequoia-grove#10]
**directive templates that need to be built**
- [x] [employee-availability.html](https://github.com/bethgrace5/sequoia-grove/blob/development/documentation/views/employee-availibility.png)**<- Beth**
- [x] [employee-info.html](https://github.com/bethgrace5/sequoia-grove/blob/development/documentation/views/employee-edit.png)
- [x] [request-history.html](https://github.com/bethgrace5/sequoia-grove/blob/development/documentation/views/requests-manager-history.png)
- [x] [request-pending.html](https://github.com/bethgrace5/sequoia-grove/blob/development/documentation/views/requests-manager-pending.png)
- [x] [request-submit.html](https://github.com/bethgrace5/sequoia-grove/blob/development/documentation/views/requests-manager-submit.png)
- [x] [schedule-delivery-edit.html](https://github.com/bethgrace5/sequoia-grove/blob/development/documentation/views/schedule-deliveries.png)
- [x] [schedule-edit.html](https://github.com/bethgrace5/sequoia-grove/blob/development/documentation/views/schedule-edit-top.png) + [other half of reference image](https://github.com/bethgrace5/sequoia-grove/blob/development/documentation/views/schedule-edit-bottom.png)**<- Beth**
- [x] [schedule-shift-edit.html](https://github.com/bethgrace5/sequoia-grove/blob/development/documentation/views/schedule-shifts.png) **<- Sunny**
- [x] [schedule-view.html](https://github.com/bethgrace5/sequoia-grove/blob/development/documentation/views/schedule-view.png)

**Comment by bethgrace5** [comment]
@jsumal do you want to finish the last view listed?

Right now, it has a form that is not linked to anything. We are already getting a list of positions from the database you can read from. This is what I can think of that needs to be done for this view:
- [x]  It still needs a save button next to the empty form.
- [x]  the inputs for times should be dropdowns instead of text edit inputs.
- [ ]  find a way to make the weekend and weekday hours the same by default.
- [x] a list repeating in the view of all of the positions below the empty form. Next to each position, there needs to be a button to delete it, and a button to edit it. 
- [x] A function to handle the delete button click needs to be setup. Clicking the delete button will eventually set the date deleted on that position in the database, but for right now, it can just log a statement to the console saying something like "deleted position id " with the position id.
- [x] A function to handle the edit button needs to be setup. If the edit button is clicked, the form above is populated with that positions info.
- [x] A function to handle the save button needs to be setup. It will eventually send the new position to the database where, regardless of it is a new position or an old one being edited, that position will then have a date deleted set, and a new one will be created with the remaining info - but the back end implementation can wait for now, just worry about the front end work, so have it log a statement saying that it saved the position.
- [ ] Find a way to have any new positions have a date started set for the beginning of the next week, and any deleted positions have an ending date as the end of the current week, so they align. We can then send these dates when we change them in the database.

Here is what currently exists - 
![screen shot 2015-12-01 at 5 57 00 pm](https://cloud.githubusercontent.com/assets/4492670/11520108/f8ef88f6-9854-11e5-9381-45b24812aa49.png)

**Comment by jsumal** [comment]
Hey Beth, yeah I can start work on this.

**Comment by bethgrace5** [comment]
This issue is outdated
