### ISSUE TITLE
Implement Requests

### ISSUE THREAD

**Issue by bethgrace5** [bethgrace5/sequoia-grove#32]
- [x] Employees need to be able to submit requests off - this means that they put a start date and end date ( the start date needs to be before the end date), and submit their request. The request must be submitted at least two weeks in advance - so the start date of the request needs to be 14 days before the current date.
- [x] Eventually, the requests need to be checked that the employee has not already submitted a request for the time span (skip this for now, and come back to it after the rest of the list is near done).
- [x] Employees need to be able to see all of their requests with their status - this means getting all requests where employee id is the id of the current logged in employee, and displaying them.
- [x] Managers need to be able to approve or deny requests - this means that a list of all pending requests should be pulled from the database, and displayed with information about the request, and a button next to each one should be there to approve or deny them. Clicking approve will remove the request and mark it as approved. Similarly, clicking deny will mark the request as denied. 
- [x] Eventually, Managers should be able to create a request for an employee, and modifiy pending requests before they become approved or denied.
- [x] Managers also should be able to see a history of all the requests - the information about requests that were approved or denied, and who approved or denied the request.

I don't think that requests that were already approved or denied should be able to change status once they've been answered.

**Comment by tpascua11** [comment]
After I finish everything Im going to do extreme polishing

**Comment by tpascua11** [comment]
All is done I think, I just need to fix the html to look better.
I need to learn about web design

**Comment by bethgrace5** [comment]
@tpascua11 great work so far! I have a few nit-pickey suggestions for you. 

## General Comments
- [x] you left a lot of debug statements in both the front and back end. Can you clean out the ones you don't need anymore.
- [x] I kind of want any dates you display to be in a more human readable format, like the ones in Employee history view. You already have a function called `defaultDate()`. Change the format string to "MMMM Do, YYYY", and call this function everywhere you display dates in request view.
- [x] `totalDays()` seems to always return one less day than the time span actually is. If a request is from the 4th of March to the 4th of March (same day) it should be one day, not zero. If a request is from the 9th of March to the 12th of March, it should be 4 days. (also `totalDays()` has some oddly named variables that are not really intuitive. consider renaming them to start and end or first and last.
- [x] you have a function called `getEmployees()` in request.js that is essentially a copy of the one in main.js. Remember that your request controller can "see" any variables in the main controller. This means that you don't need a separate copy of the employee list in request.js, you can just reference the one in main.js. - put simply, 1. delete that function in request.js, and 2. delete that declaration for employees in request.js.
- [x] `pending` requests should not show up in the request history list. Those are already shown above in the pending list. 
- [x] this is a small change: it says ".parent" on the schedule view. This looks like a debug statement, and probably should be removed. 

## Database Views
- You'll have to create a view in the database to achieve the following, and probably make some modifications to the java classes that use the following - I'm not sure how comfortable you are with database views. I can give you a jump start on it if you need. Let me know.
- [x] In pending requests, the employee that the request is for should show their name, not their id. This means you might have to build a view to join the employee name to the request table.
- [x] same thing for Request History, it should show the name of the employee who submitted the request, not the id. It should also show the name of the manager that approved or denied the request, not their id.

## UI Fixes
- I want to work with you on the following issues, so don't start on them yet. These mostly have to do with UI fixes, which you don't seem very strong in yet, so I want to teach you how to work on them when you have time.
- [x] this one isn't really that important, it can wait until other things are done), modify pending request doesn't seem to be working. I have ideas on how to elegantly implement the ability to modify the requests, and I'd like to sit down to work with you on making this better before you fix it.
- [x] the manager's view seems functional, but it could use a makeover, and I have some ideas for it.
- [x] one thing I want to teach you is how to show immediate feedback, for example, if I submit a request, and click the submit button, I should see it immediately appear in my list with a status as pending. I shouldn't have to refresh the page to see it. This is really just a front end trick that re-assures the user that their request was submitted. More on this when we work together.
- [x] one small thing that was bugging me was the vertical scroll that is the entire width of the screen. If I try to scroll down the page, I get stuck scrolling in requests. We just need to make the container slightly smaller and centered in the page. I'll show you how to do this.
