### ISSUE TITLE
Implement Holidays

### ISSUE THREAD

**Issue by bethgrace5** [bethgrace5/sequoia-grove#34]
There are days that the store is closed for a half or full day. There exists a table in the database for this, but it is not connected to the front end yet. The managers need to be able to input holidays (name of holiday, date, full or half day). The schedule should block out shifts that occur during a holiday. The table may need to have a column for the time that the half day ends, so it will know which shifts to block out. Different stores may have different ending times, so this will need to be added to the database.
- [x] - input date, name, type for new holiday
- [x] - view list of current holidays
- [x] - edit/delete holidays
- [x] - the schedule displays the holiday, and doesn't allow manager to schedule shifts that are during the holiday.

**Comment by tpascua11** [comment]
- [x] Remove any Holiday UI from the schedule page

Put the UI in the manage page with the following inputs       
- [ ] Holiday Name  
- [ ] DatePicker - select date
- [ ] Select Box -- Open Time
- [ ] Select Box -- Close Time

Reformat bajs_holidays table to have those columns listed.
- [x] Holiday -[date]
- [x] Store-Open - [varChar(4)]
- [x] Store-Closed - [varChar(4)]
- [x] Title - [varChar(64)]
