### ISSUE TITLE
Clearing the schedule shoudn't automatically save as it does

### ISSUE THREAD

**Issue by bethgrace5** [bethgrace5/sequoia-grove#44]
It should clear the front end, but not save until save is clicked.

**Comment by bethgrace5** [comment]
@jsumal I believe I have fixed this issue as well as #28 with this branch:
https://github.com/bethgrace5/sequoia-grove/tree/feature-clear-schedule

When you have time, would you pull the branch, and verify that both issues are fixed 

Here is what you should do - get your working directory in a clean state, so you can get the new branch, then:
- `git co development; git pull origin development` to get any latest code
- `git fetch` to get a reference to the remote branch
- `git co feature-clear-schedule` to jump over to the new branch
- run the app, and verify that the issues are fixed, and it still works as expected
- [x]  It should still save names that are changed, but if a name is blank, it should be saved as blank when the save schedule button is clicked. 
- [x] When clear is clicked, it clears the schedule, but doesn't save until save is clicked.
- `git co development; git merge feature-clear-schedule` to merge the branch in to development
- _close #44 and #28_ (or you could append "closes #44, closes #28" to the auto commit message it gave you when you merged the branch into development, and it will close it for you, which is super cool, but going to the issues, and commenting that they are fixed and closing them works too)
- if it merged into development, `git push origin --delete feature-clear-schedule` to delete the remote branch.
- you also might want to delete your local branch `git branch -D feature-clear-schedule`

**Comment by jsumal** [comment]
can't seem to import from last week, will try again after class

**Comment by bethgrace5** [comment]
@jsumal ok, thanks I'll look into that.

**Comment by bethgrace5** [comment]
@jsumal I believe I fixed the issue - will you verify?

**Comment by jsumal** [comment]
@bethgrace5 okay it looks good, nice job
