### ISSUE TITLE
Implement Date Pickers

### ISSUE THREAD

**Issue by bethgrace5** [bethgrace5/sequoia-grove#45]
All of the date inputs are currently plain text inputs - a library needs to be found for angular date picker, installed with bower, and implemented to return the format needed to send with requests.

**Comment by tpascua11** [comment]
For the datepicker,  wouldn't it become a bit hard to select your birth date?

**Comment by bethgrace5** [comment]
@tpascua11 that is a good point. We need a way to force the users enter the date in a specific format. I think a date picker is the best way to do so, but if you have a better idea, we can look at it.
