### ISSUE TITLE
Host Webapp

### ISSUE THREAD

**Issue by jsumal** [bethgrace5/sequoia-grove#58]
Move the webapp to AWS for hosting the project on the internet.

**Comment by bethgrace5** [comment]
Fortunately, sleipnir has tomcat installed, and the application can be hosted there, but there are some issues with java version compatibility. Steve updated sleipnir to have java 1.8, which is what I'm using to compile and run on my machine, but that didn't fix the compatibility problem. I think it may have to do with the version of tomcat. The verification for Mozilla Persona seems to be the only class affected, so if I remove that class and as a result, the log in security as well, it works as it should, without login security.

**Comment by bethgrace5** [comment]
barring issues with java annotation compatibility that seems to only clutter the log file, the application runs as expected on sleipnir.

`Mar 28, 2016 11:40:25 AM org.apache.catalina.startup.ContextConfig processAnnotationsJar
SEVERE: Unable to process Jar entry [jdk/nashorn/internal/objects/NativeDataView$Prototype.class] from Jar [jar:file:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar!/] for annota
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 15`
