### ISSUE TITLE
Scheduling UI/UX

### ISSUE THREAD

**Issue by jsumal** [bethgrace5/sequoia-grove#60]
- need a way to easily visualize which shifts and time slots an employee can be scheduled for when their name is clicked
- need way to easy visualize which employees can be scheduled for a blank time slot, perhaps my providing a list of names in a tool tip when the mouse hovers over it

**Comment by bethgrace5** [comment]
@jsumal I had given some thought to this, and I believe the best solutions is that when the name is clicked **in the list on the right hand side**, it should highlight all of the spots they can be scheduled for in a different shade than the names that highlight when that employee is selected, so when the name is clicked there, you should see one shade showing all the spots they are currently scheduled for (what it does already), and another shade shows all the spots they could possibly be scheduled for.

**Comment by bethgrace5** [comment]
I think tool tips are best saved for displaying the error/warning messages, should it be the case that the employee was scheduled for a spot they actually cannot work.
